version: "3.9"

services:
  application:
    container_name: yandex-lavka-app
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      POSTGRES_DSN: postgresql://postgres:password@db/postgres
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - db
    networks:
      - enrollment

  db:
    container_name: yandex-lavka-db
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    restart: always
    networks:
      - enrollment

networks:
  enrollment:
    driver: bridge
